# Model Training

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# modelling
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score,  mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
# from catbost import CatBoostRegression
# from xgboost import XGBRegressor

import warnings
warnings.filterwarnings('ignore')

Import the CSV Data as Pandas DataFrame

In [7]:
df = pd.read_csv('data/stud.csv')
df.head(3)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

Preparingf X and Y variables

In [9]:
x = df.drop(columns=['math_score'])
y = df['math_score']

In [10]:
x.head(3)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93

In [11]:
y.head(2)

0    72
1    69
Name: math_score, dtype: int64